[phases.setup]
nixPkgs = ["php82", "nodejs"]

[phases.install]
cmds = [
  "install-php-extensions gd exif",
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
  "npm ci",
  "npm run build"
]
